apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: kube-prometheus-stack
    name: in-cluster
  project: monitoring
  source:
    path: apps/kube-prometheus-stack
    repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
    targetRevision: main
    plugin: 
      name: kustomized-helm
      env: 
        - name: HELM_RELEASE_NAME
          value: "kube-prometheus-stack"
        - name: HELM_REPO_NAME
          value: "kube-prometheus-stack"
        - name: HELM_REPO_URL
          value: "https://prometheus-community.github.io/helm-charts"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
