apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: kube-prometheus-stack
    path: apps/kube-prometheus-stack
    helm:
      values: |-
        kubeApiServer:
          enabled: true
        kubeControllerManager:
          enabled: true
          endpoints:
          - 10.0.1.101
        kubeScheduler:
          enabled: true
          endpoints:
          - 10.0.1.101
        kubeProxy:
          enabled: true
          endpoints:
          - 10.0.1.101
        kubeEtcd:
          enabled: true
          endpoints:
          - 10.0.1.101
          service:
            enabled: true
            port: 2381
            targetPort: 2381
        alertmanager:
          service:
            type: ClusterIP
        prometheus:
          service:
            type: ClusterIP
        grafana:
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              # cert-manager.io/issuer: prod-issuer
              # cert-manager.io/issuer-kind: OriginIssuer
              # cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
            hosts:
            - grafana.cluster.arpa
            # tls:
            # # specifying a host in the TLS section will tell cert-manager what
            # # DNS SANs should be on the created certificate.
            # - hosts:
            #     - grafana.integratn.tech
            #   # cert-manager will create this secret
            #   secretName: grafana-integratn-tech-tls
        prometheus-node-exporter:
          hostRootFsMount:
            enabled: false
        prometheusOperator:
          admissionWebhooks:
            failurePolicy: Ignore
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 48.1.0
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
