- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --kubelet-insecure-tls
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: ----requestheader-client-ca-file=/ca/ca.pem
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: ca-pem
    secret:
      secretName: ca-pem
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: ca-pem
    mountPath: /ca
