namespace: rook-ceph
resources:
  - crds.yaml
  - common.yaml
  - operator.yaml
  - cluster.yaml

patches:
  - patch: |-
      - op: add
        path: /metadata/labels
        value: pod-security.kubernetes.io/audit: privileged
    target:
      kind: Namespace