namespace: rook-ceph
resources:
  - crds.yaml
  - common.yaml
  - operator.yaml
  - cluster.yaml
  - toolbox.yaml
  - ingress.yaml
  - ceph-block-pool.yaml
  - storageclass.yaml

patches:
  - path: namespace.yaml
    target:
      kind: Namespace