kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-sonarr-local
  namespace: media
  labels:
    app: sonarr
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi