kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-sonarr
  namespace: media
  labels:
    app: sonarr
spec:
  storageClassName: config-nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: config-sonarr