apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: k8s-sigs.io/config-nfs-subdir-external-provisioner
  name: config-sonarr
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/user/appdata/sonarr
    server: 10.0.0.10
  persistentVolumeReclaimPolicy: Retain
  storageClassName: config-nfs-client
  volumeMode: Filesystem
