kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads-tv
  namespace: media
  labels:
    app: sonarr
spec:
  storageClassName: data-nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: downloads-tv