apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: k8s-sigs.io/data-nfs-subdir-external-provisioner
  name: downloads-tv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/user/data/usenet/tv
    server: 10.0.0.10
  persistentVolumeReclaimPolicy: Retain
  storageClassName: data-nfs-client
  volumeMode: Filesystem
status: