kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads-tv
  namespace: media
  labels:
    app: sonarr
  annotations:
    nfs.io/storage-path: "tv/" # not required, depending on whether this annotation was shown in the storage class description
spec:
  storageClassName: data-nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: downloads-tv