kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-tv
  namespace: media
  labels:
    app: sonarr
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: media-tv