apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pi4-cluster
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git:secret:github.com-jamesatintegratnio-homelab/sshPrivateKey
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: infra
  source:
    repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
    targetRevision: HEAD
    path: clusters/pi4-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: pi4-cluster
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
