apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: pi4-cluster
  namespace: pi4-cluster
spec:
  replicas: 1
  version: v1.27.2-k0s.0
  # k0sConfigSpec:
  #   k0s:
  #     apiVersion: k0s.k0sproject.io/v1beta1
  #     kind: ClusterConfig
  #     metadata:
  #       name: k0s
  #     spec:
  #       api:
  #         extraArgs:
  #           anonymous-auth: "true"
  # machineTemplate:
  #   infrastructureRef:
  #     apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
  #     kind: RemoteMachineTemplate
  #     name: pi4-cluster-remote-machine-template
  #     namespace: pi4-cluster
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: pi4-cluster
  namespace: pi4-cluster
spec:
  replicas: 4
  clusterName: pi4-cluster
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: pi4-cluster
      pool: default
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: pi4-cluster
        pool: default
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: K0sWorkerConfigTemplate
          name: pi4-cluster
          namespace: pi4-cluster
      clusterName: pi4-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: RemoteMachineTemplate
        name: pi4-cluster-remote-machine-template
        namespace: pi4-cluster
      version: v1.27.2-k0s.0
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: pi4-cluster
  namespace: pi4-cluster
spec:
  template:
    spec:
      version: v1.27.2-k0s.0
