apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfig
metadata:
  name: pi4-cluster-workconfig
  namespace: pi4-cluster
spec:
  version: v1.27.12+k0s.0 
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name:  pi4-cluster-1
  namespace: pi4-cluster
spec:
  clusterName: pi4-cluster
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
      kind: K0sWorkerConfig
      name: pi4-cluster-workconfig
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteMachine
    name: pi4-cluster-1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachine
metadata:
  name: pi4-cluster-1
  namespace: pi4-cluster
spec:
  address: 10.0.3.101
  port: 22
  user: root
  sshKeyRef:
    name: ssh-key-secret
# ---
# apiVersion: cluster.x-k8s.io/v1beta1
# kind: Machine
# metadata:
#   name:  pi4-cluster-2
#   namespace: pi4-cluster
# spec:
#   clusterName: pi4-cluster
#   bootstrap:
#     configRef:
#       apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
#       kind: K0sWorkerConfig
#       name: pi4-cluster-workconfig
#   infrastructureRef:
#     apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
#     kind: RemoteMachine
#     name: pi4-cluster-2
# ---
# apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
# kind: RemoteMachine
# metadata:
#   name: pi4-cluster-2
#   namespace: pi4-cluster
# spec:
#   address: 10.0.3.102
#   port: 22
#   user: root
#   sshKeyRef:
#     name: ssh-key-secret
# ---
# apiVersion: cluster.x-k8s.io/v1beta1
# kind: Machine
# metadata:
#   name:  pi4-cluster-3
#   namespace: pi4-cluster
# spec:
#   clusterName: pi4-cluster
#   bootstrap:
#     configRef:
#       apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
#       kind: K0sWorkerConfig
#       name: pi4-cluster-workconfig
#   infrastructureRef:
#     apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
#     kind: RemoteMachine
#     name: pi4-cluster-3
# ---
# apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
# kind: RemoteMachine
# metadata:
#   name: pi4-cluster-3
#   namespace: pi4-cluster
# spec:
#   address: 10.0.3.103
#   port: 22
#   user: root
#   sshKeyRef:
#     name: ssh-key-secret
# ---
# apiVersion: cluster.x-k8s.io/v1beta1
# kind: Machine
# metadata:
#   name:  pi4-cluster-4
#   namespace: pi4-cluster
# spec:
#   clusterName: pi4-cluster
#   bootstrap:
#     configRef:
#       apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
#       kind: K0sWorkerConfig
#       name: pi4-cluster-workconfig
#   infrastructureRef:
#     apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
#     kind: RemoteMachine
#     name: pi4-cluster-4
# ---
# apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
# kind: RemoteMachine
# metadata:
#   name: pi4-cluster-4
#   namespace: pi4-cluster
# spec:
#   address: 10.0.3.104
#   port: 22
#   user: root
#   sshKeyRef:
#     name: ssh-key-secret
# ---
# apiVersion: cluster.x-k8s.io/v1beta1
# kind: Machine
# metadata:
#   name:  pi4-cluster-5
#   namespace: pi4-cluster
# spec:
#   clusterName: pi4-cluster
#   bootstrap:
#     configRef:
#       apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
#       kind: K0sWorkerConfig
#       name: pi4-cluster-workconfig
#   infrastructureRef:
#     apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
#     kind: RemoteMachine
#     name: pi4-cluster-5
# ---
# apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
# kind: RemoteMachine
# metadata:
#   name: pi4-cluster-5
#   namespace: pi4-cluster
# spec:
#   address: 10.0.3.105
#   port: 22
#   user: root
#   sshKeyRef:
#     name: ssh-key-secret
# ---