---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: pi4-cluster
  namespace: pi4-cluster
spec:
  replicas: 4
  clusterName: pi4-cluster
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: pi4-cluster
      pool: default
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: pi4-cluster
        pool: default
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: K0sWorkerConfigTemplate
          name: pi4-cluster
          namespace: pi4-cluster
      clusterName: pi4-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: RemoteMachineTemplate
        name: pi4-cluster-remote-machine-template
        namespace: pi4-cluster
      version: v1.27.2-k0s.0
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: pi4-cluster
  namespace: pi4-cluster
spec:
  template:
    spec:
      version: v1.27.12+k0s.0 
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachineTemplate
metadata:
  name: pi4-cluster-remote-machine-template
  namespace: pi4-cluster
spec:
  template:
    spec:
      pool: default
# ---
# apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
# kind: PooledRemoteMachine
# metadata:
#   name: pi4-cluster-1
#   namespace: pi4-cluster
# spec:
#   pool: default
#   machine:
#     address: 10.0.3.101
#     port: 22
#     user: root
#     sshKeyRef:
#       name: ssh-key-secret
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PooledRemoteMachine
metadata:
  name: pi4-cluster-2
  namespace: pi4-cluster
spec:
  pool: default
  machine:
    address: 10.0.3.102
    port: 22
    user: root
    sshKeyRef:
      name: ssh-key-secret
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PooledRemoteMachine
metadata:
  name: pi4-cluster-3
  namespace: pi4-cluster
spec:
  pool: default
  machine:
    address: 10.0.3.103
    port: 22
    user: root
    sshKeyRef:
      name: ssh-key-secret
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PooledRemoteMachine
metadata:
  name: pi4-cluster-4
  namespace: pi4-cluster
spec:
  pool: default
  machine:
    address: 10.0.3.104
    port: 22
    user: root
    sshKeyRef:
      name: ssh-key-secret
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PooledRemoteMachine
metadata:
  name: pi4-cluster-5
  namespace: pi4-cluster
spec:
  pool: default
  machine:
    address: 10.0.3.105
    port: 22
    user: root
    sshKeyRef:
      name: ssh-key-secret
