apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect
spec:
  replicas: 0
  selector:
    matchLabels:
      app: onepassword-connect
  template:
    metadata:
      labels:
        app: onepassword-connect
        version: "1.0.0"
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: op-connect-pvc
        - name: credentials
          secret:
            secretName: op-credentials
      initContainers:
        - name: sqlite-permissions
          securityContext:
            runAsUser: 999
          image: alpine:3.12
          command:
            - "/bin/sh"
            - "-c"
          args:
            - "mkdir -p /home/opuser/.op/data && mkdir -p /home/opuser/.op/config && chown -R 999 /home/opuser && chmod -R 700 /home/opuser && chmod -f -R 600 /home/opuser/.op/config || :"
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
      containers:
        - name: connect-api
        
          image: 1password/connect-api:latest
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 999
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.4"
          ports:
            - containerPort: 8080
          env:
            - name: OP_SESSION
              value: /home/opuser/.config/1password-credentials.json
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
            - mountPath: /home/opuser/.config
              name: credentials
              readOnly: true
        - name: connect-sync
          image: 1password/connect-sync:latest
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 999
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.4"
          ports:
            - containerPort: 8081
          env:
            - name: OP_HTTP_PORT
              value: "8081"
            - name: OP_SESSION
              value: /home/opuser/.config/1password-credentials.json
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
            - mountPath: /home/opuser/.config
              name: credentials
              readOnly: true