kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: op-connect-pvc
  namespace: op-connect
  labels:
    app: onepassword-connect
spec:
  storageClassName: data-nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: op-connect-pv