apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: test-secret #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/c74zxv7vnwdixfpuw3lawaijvu/allitems/x2hhhzsam2emguuu5srll7e6du"