apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: infra-stack
  description: |
    The domain for infrastructure services
spec:
  owner: group:default:engineering
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: argocd
  description: |
    ArgoCD is a declarative, GitOps continuous delivery tool for Kubernetes.
spec:
  owner: group:default:engineering
  domain: infra-stack
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage
  description: |
    Backstage is an open platform for building developer portals
spec:
  owner: group:default:engineering
  domain: infra-stack

---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-manifests
  description: |
    Pointer to the backstage manifest and linked resources
spec:
  targets:
    - apps/backstage/catalog-info.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage-db
  description: |
    Database for backstage persistance
  links:
    - title: Control Panel
      url: https://10.0.3.1
    - title: Web Shell
      url: https://10.0.3.1:12320/
    - title: Adminer
      url: https://10.0.3.1:12322/
spec:
  owner: group:default:engineering
  type: database
  lifecycle: homeprod
