apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: infra-stack
  description: |
    The domain for infrastructure services
spec:
  owner: group:default:engineering
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: argocd
  description: |
    ArgoCD is a declarative, GitOps continuous delivery tool for Kubernetes.
spec:
  owner: group:default:engineering
  domain: infra-stack
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage
  description: |
    Backstage is an open platform for building developer portals
spec:
  owner: group:default:engineering
  domain: infra-stack
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage-manifests
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: service
      url: https://backstage.k8s.integratn.tech
    - title: Manifests
      url: https://github.com/jamesatintegratnio/homelab/tree/main/apps/backstage
  
spec:
  type: kubernetes-manifest
  owner: group:default:engineering
  lifecycle: homeprod
  system: backstage
  children:

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage-db
  description: |
    Database for backstage persistance
  links:
    - title: Control Panel
      url: https://10.0.3.1
    - title: Web Shell
      url: https://10.0.3.1:12320/
    - title: Adminer
      url: https://10.0.3.1:12322/
spec:
  owner: group:default:engineering
  type: database
  lifecycle: homeprod
  system: backstage