apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-management-cluster
spec:
  hosts:
  - ssh:
      address: 10.0.2.101
      user: boboysdadda
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: controller+worker
    noTaints: true
    environment:
      DISABLE_TELEMETRY: true
    hooks:
      apply:
        before:
        - sudo mkdir -p /var/log/k0s/audit && sudo chmod -R 770 /var/log/k0s/audit
  - ssh:
      address: 10.0.2.102
      user: boboysdadda
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: worker
    environment:
      DISABLE_TELEMETRY: true
    hooks:
      apply:
        before:
        - sudo mkdir -p /var/log/k0s/audit && sudo chmod -R 770 /var/log/k0s/audit
  - ssh:
      address: 10.0.2.103
      user: boboysdadda
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: worker
    environment:
      DISABLE_TELEMETRY: true
    hooks:
      apply:
        before:
        - sudo mkdir -p /var/log/k0s/audit && sudo chmod -R 770 /var/log/k0s/audit
  k0s:
    version: null
    # versionChannel: stable
    dynamicConfig: false
    config: {}

