apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: prod-issuer
  namespace: cert-manager
spec:
  requestType: OriginECC
  auth:
    serviceKeyRef:
      name: cloudflare-service-key
      key: key