#              uuuuuuuuuuuuuuuuuuuu
#            u" uuuuuuuuuuuuuuuuuu "u
#          u" u$$$$$$$$$$$$$$$$$$$$u "u
#        u" u$$$$$$$$$$$$$$$$$$$$$$$$u "u
#      u" u$$$$$$$$$$$$$$$$$$$$$$$$$$$$u "u
#    u" u$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$u "u
#  u" u$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$u "u
#  $ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ $
#  $ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ $
#  $ $$$" ... "$...  ...$" ... "$$$  ... "$$$ $
#  $ $$$u `"$$$$$$$  $$$  $$$$$  $$  $$$  $$$ $
#  $ $$$$$$uu "$$$$  $$$  $$$$$  $$  """ u$$$ $
#  $ $$$""$$$  $$$$  $$$u "$$$" u$$  $$$$$$$$ $
#  $ $$$$....,$$$$$..$$$$$....,$$$$..$$$$$$$$ $
#  $ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ $
#  "u "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$" u"
#    "u "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$" u"
#      "u "$$$$$$$$$$$$$$$$$$$$$$$$$$$$" u"
#        "u "$$$$$$$$$$$$$$$$$$$$$$$$" u"
#          "u "$$$$$$$$$$$$$$$$$$$$" u"
#            "u """""""""""""""""" u"
#              """"""""""""""""""""
#
#  If you do not know what you are doing DO NOT EDIT THIS FILE.
#  ArgoCD is inherently dangerous. Think of it like a grenade. 
#  It has the power to completely wipe out an environment in seconds, 
#  if it's configuration instructs it to do so. This ApplicationSet defines 
#  all of the applications for a given ArgoCD installation. If a 
#  destructive change to this ApplicationSet is made, the results 
#  could be devastating.
#
#  If you are unsure of what to do. Don't do what James would do....
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:

  name: argo-stack
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
        - clusters: {}
        - list:
            elements:
              - appName: argocd
                namespace: argocd
                syncWave: 1
              - appName: argo-workflow
                namespace: argo-workflow
                syncWave: 1
              - appName: argocd-applications
                namespace: argocd
                syncWave: 2
              - appName: argocd-image-updater
                namespace: argocd
                syncWave: 2
  template:
    metadata:
      name: "{{.name}}-{{.appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
        argocd.argoproj.io/sync-wave: "{{.syncWave}}"
    spec:
      project: infra
      source:
        repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
        targetRevision: argocd
        path: "argocd/{{.appName}}/overlays/{{.name}}"
      destination:
        name: in-cluster
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      destination:
        {{- if eq .childClusters true}}
        name: "{{.name}}"
        {{- else }}
        name: "in-cluster"
        {{- end }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          {{- if eq .syncPolicy "replace" }}
          - Replace=true
          {{- end }}