apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:

  name: infra-stack
  namespace: argocd
spec:
  goTemplate: true
  # goTemplateOptions: [ "missingkey=error" ]
  generators:
  - matrix:
      generators:
        - clusters: {}
        - git: 
            repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
            revision: main
            files:
              - path: "core/**/config.json"
  template:
    metadata:
      name: "{{.name}}-{{.path.basename}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
        argocd.argoproj.io/sync-wave: "{{.syncwave}}"
    spec:
      project: infra
      source:
        repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
        targetRevision: infra
        path: "core/{{.path.basename}}/overlays/{{.name}}"
      destination:
        name: "{{.name}}"
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      {{- if ne nil $.ignoreDifferences }}
        ignoreDifferences: 
          {{.ignoreDifferences}}
      {{- end }}

