#              uuuuuuuuuuuuuuuuuuuu
#            u" uuuuuuuuuuuuuuuuuu "u
#          u" u$$$$$$$$$$$$$$$$$$$$u "u
#        u" u$$$$$$$$$$$$$$$$$$$$$$$$u "u
#      u" u$$$$$$$$$$$$$$$$$$$$$$$$$$$$u "u
#    u" u$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$u "u
#  u" u$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$u "u
#  $ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ $
#  $ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ $
#  $ $$$" ... "$...  ...$" ... "$$$  ... "$$$ $
#  $ $$$u `"$$$$$$$  $$$  $$$$$  $$  $$$  $$$ $
#  $ $$$$$$uu "$$$$  $$$  $$$$$  $$  """ u$$$ $
#  $ $$$""$$$  $$$$  $$$u "$$$" u$$  $$$$$$$$ $
#  $ $$$$....,$$$$$..$$$$$....,$$$$..$$$$$$$$ $
#  $ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ $
#  "u "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$" u"
#    "u "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$" u"
#      "u "$$$$$$$$$$$$$$$$$$$$$$$$$$$$" u"
#        "u "$$$$$$$$$$$$$$$$$$$$$$$$" u"
#          "u "$$$$$$$$$$$$$$$$$$$$" u"
#            "u """""""""""""""""" u"
#              """"""""""""""""""""
#
#  If you do not know what you are doing DO NOT EDIT THIS FILE.
#  ArgoCD is inherently dangerous. Think of it like a grenade. 
#  It has the power to completely wipe out an environment in seconds, 
#  if it's configuration instructs it to do so. This ApplicationSet defines 
#  all of the applications for a given ArgoCD installation. If a 
#  destructive change to this ApplicationSet is made, the results 
#  could be devastating.
#
#  If you are unsure of what to do. Don't do what James would do....
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:

  name: monitoring-stack
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
        - clusters: {}
        - list:
            elements:
              - appName: loki
                namespace: monitoring
                project: monitoring
              - appName: promtail
                namespace: monitoring
                project: monitoring
              - appName: prometheus
                namespace: monitoring
                project: monitoring
              - appName: grafana
                namespace: monitoring
                project: monitoring
              - appName: starboard-operator
                namespace: monitoring
                project: monitoring
  ignoreApplicationDifferences:
  - jsonPointers:
    - /spec/syncPolicy/automated           
  template:
    metadata:
      name: "{{.name}}-{{.appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: "{{.project}}"
      source:
        repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
        targetRevision: monitoring
        path: "monitoring/{{.appName}}/overlays/{{.name}}"
      destination:
        name: in-cluster
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
        managedNamespaceMetadata:
          labels:
            goldilocks.fairwinds.com/enabled: "true"  
  templatePatch: |
    spec:
      destination:
        {{- if eq .childClusters true}}
        name: "{{.name}}"
        {{- else }}
        name: "in-cluster"
        {{- end }}
