namespace: op-connect
labels:
  - pairs:
      'backstage.io/kubernetes-id': 'op-connect-helm'
resources:
  - namespace.yaml

patches:
  - target:
      group: v1
      version: v1
      kind: Namespace
    patch: |
      - op: add
        path: /metadata/labels
        value:
          goldilocks.fairwinds.com/enabled: "true"