---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: onepassword-token
  namespace: op-connect
spec:
  encryptedData:
    token: AgA5ts6xF1T0Z4KE3kEmue2nWCJN7pt86K/PI3H9ZVBHtdNpjdiglZ9YHuFsp35cjyeYfZH7WBdEP0eXe0RK/sdzndv1eoyg/ZGTbAaCdij/gL4ayZOuedwpFWyz98R5wrU/2CCSSD72QFhD6zn2ZVhqoj67bggZjyICkfERjFX4TFFYflpUQHvUvinRoC+24ie2xm+dzyYKQYz3zf+eLuizNd60kgrbeWIS8yjBJdDACoVc/ake+NAziydqKoyXiQYSzPI7pqvhfjGrxuyhVz3yGdjoh8AybY5Dtdamm5MPUP/BALrearspTeTye9nSOti9mQ+Y5KEdVN1WvC2A01DmYBB8ovOeeBjgjQzDd7U2uhIfpvqmunDHfAdaVbZsmjW9ZngiU/Z140mIM1Sz1g4BcOm0ZFdexH4r70JLmhpfv9x4UnL+m6PlT388fB6o1hzNRn07/GWOuM65vXAY4KWzOjlo2BMrfIZWdEyfbNiki0kksBMDNmZviv/Cuv8L0YdZzWVWiJ/beK8UjPeBtzW6Liggdc+BfoC9T9a9tPujGLeWnR5siwAd2HTzfPrv1pJ2CrYHUqAhJkVE992ddegf9LSxUkmzRErzdU3Euvh9JFwesZqq+EGKfYdUHqJynJIUHwRsLgeHtyQd3DBvDGOk8eVBGluwTboWVrky9LG5s4ntkOrdOMNN0Z8oQy/V9PZz72VyPA+RWIj8gOuFv4+dRdd4hQqv4qkXWm49sOHAkGHaagnNg0P0PmyyYJ3VBzA3letIWcS2d3Dh9Hv4OrF+HrLGn8RmYoMq2Hl8L8M0R+CKjUnHnBVBVYYEYEeJZWoLgBxft6ZemDqqqGm1VSamXesxDzazu7XaCNvr/mKlTCjKVVC7eoGAXedlVOvDnZTTxPcuoZ57txXP3peVRN5BD6sHg++g2Ky7E+Ynx6OvmflUPPojbktxSsw0yO0gHqbRQBdxLtXAKyo2KFoXLKTYPbe51xDtTUL1gGk+ApNVnCR/Qocb8Q6SlK/fPGsrqvuwVosKOrEnZhI/ZTr1olH+hru3oUaWmIRUEfKzfBogcKhp1UQlErLG7WgCGRa7x/oqNl70CAth0nOTVprLG/Qz9fD7MV7lWhODf1m1IVZGpMI+jjyoruJRqXVAS/80TH5FDuK4LCIgOEqgGyoNyv0e5ovCiCN55Ao8IvjO6D4XSiZX7wU3hokQjItI8odzaYWIGW8ZuByA1l7oSsT/70+z1U9tCli1d6BkzEIGcnQdrncuZPoTkSDbHeSywEvQaie5ui0dSWsXU70u8ldSpPvbtfu4AQbz+KhCXLLBeU/KnDAx0C68tSI4svE//NflFbXMs/iHriYSGer3gwTEw5xF0hSjzr7H/ypaRYRC1RtHbACKcSO69CevrfWGcisBYFBPV3HCr8F35VUUKHdheO69O9jeEl3sgUPzmR4enYgb9AG+Sea9bWIFnkm9FriGfkGLkPw1oDoXFcQbGgbQLrkXordWnBGWuvtLqkOERdKrnySoX8v52jhCEsaAJ/SBc7iK0EbcdIhcLydmPZWRV+P9aO4=
  template:
    metadata:
      creationTimestamp: null
      name: onepassword-token
      namespace: op-connect
