resources:
  - home-assistant-secrets.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - files:
    - configuration.yaml
    name: home-assistant-config
  - files:
    - automations.yaml
    name: home-assistant-automations
  - files:
    - scenes.yaml
    name: home-assistant-scenes
  - files:
    - scripts.yaml
    name: home-assistant-scripts
generatorOptions:
  disableNameSuffixHash: true