apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: l2_address_pool_patch.yaml
  target:
    group: metallb.io
    version: v1beta1
    kind: IPAddressPool
    name: default
    namespace: metallb-system
- path: ignore-differences-patch.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: in-cluster-metallb
    namespace: argocd