resources:
  - home-assistant-mysql-db-secret.yaml
  - home-assistant-secrets.yaml
  - db.yaml
  # - pvc.yaml
  - deployment.yaml

configMapGenerator:
  - files:
    - configuration.yaml
    name: home-assistant-config