kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-pvc
  namespace: home-assistant
  labels:
    app: home-assistant
spec:
  storageClassName: directpv-min-io
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi