kind: Service
metadata:
  labels:
    app: home-assistant
  name: home-assistant-service
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 8123
  selector:
    app: home-assistant
  type: ClusterIP