apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: kustomized-helm
spec:
  init:
    command: [sh, /var/run/argocd/helm-kustomize-plugin/init.sh]
  
  generate:
    command: [sh, /var/run/argocd/helm-kustomize-plugin/generate.sh]
    