# kubectl create secret generic pihole-password --from-literal EXTERNAL_DNS_PIHOLE_PASSWORD=mySecretPassword -n external-dns
# TODO: make this an sealed-secret
namespace: external-dns
labels:
  - pairs:
      'backstage.io/kubernetes-id': 'external-dns'
resources:
- https://github.com/kubernetes-sigs/external-dns.git//kustomize
- namespace.yaml
- pihole-password-onepasswordItem.yaml
patches:
- path: deployment_patch.yaml
  target: 
    group: apps
    version: v1
    kind: Deployment
    name: external-dns
