apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hajimari
  namespace: argocd
  annotations: 
spec:
  project: infra
  source:
    repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
    targetRevision: HEAD
    path: apps/hajimari
    plugin:
      name: kustomized-helm
      env: 
        - name: HELM_RELASE_NAME
          value: hajimari
        - name: HELM_REPO_NAME
          value: hajimari
        - name: HELM_REPO_URL
          value: https://hajimari.io
  destination:
    name: in-cluster
    namespace: hajimari
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true