apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hajimari
  namespace: argocd
  annotations: 
    argocd-image-updater.argoproj.io/write-back-method: kustomization
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: hajimari
spec:
  project: infra
  source:
    repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
    targetRevision: HEAD
    path: apps/hajimari
    plugin:
      name: kustomized-helm
  destination:
    name: in-cluster
    namespace: hajimari
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true