ingress:
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    ingressClassName: "nginx"
    tls:
    - hosts:
      - hajimari.cluster.integratn.tech
      secretName: argocd-tls
    hosts:
    - host: hajimari.cluster.integratn.tech
      paths:
        - path: /
          pathType: Prefix
persistence:
  data:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi