apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: This project collects all of the monitoring services together
  destinations:
  - name: "in-cluster"
    namespace: "monitoring"
  - name: "in-cluster"
    namespace: "kube-system"
  - name: "in-cluster"
    namespace: "kube-prometheus-stack"
  - name: "in-cluster"
  sourceRepos:
  - '*'
  sourceNamespaces:
  - "monitoring"
  - kube-system
