namespace: argocd
labels:
  - pairs:
      'backstage.io/kubernetes-id': 'argocd-image-updater'
resources:
  - github.com/argoproj-labs/argocd-image-updater/manifests/base/?rev=master
  - argocd-image-updater-secret.yaml

patches:
  - path: argocd-image-updater-config-cm-patch.yaml
    target:
      labelSelector: "app.kubernetes.io/name=argocd-image-updater-config"