all:
  hosts:
  # I know this looks dumb, but for some reason my router gives 
  # them all the same IP address and I can only address one at a time.
  # use `ansible-playbook -i hosts.yaml playbook.yaml --limit pi-cluster-1` to target a specific machine
  # as its the only way to make this work

    k8s-master:
      ansible_host: 10.0.2.101
      static_ip: 10.0.2.101
    k8s-worker1:
      ansible_host: 10.0.2.102
      static_ip: 10.0.2.102
    k8s-worker2:
      ansible_host: 10.0.2.103
      static_ip: 10.0.2.103

  vars:
    ansible_user: boboysdadda
    ansible_ssh_private_key_file: /home/boboysdadda/.ssh/id_ed25519
    ansible_become: yes
    ansible_become_method: sudo