---
- name: Update and upgrade packages
  hosts: all
  become: true

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
    - name: install nfs-common
      apt:
        name: nfs-common
        state: present

    - name: Set static IP with netplan
      copy:
        content: |
          network:
            version: 2
            ethernets:
              ens18:
                dhcp4: no
                link-local: [ ipv4 ]
                addresses: [{{ static_ip }}/9]
                routes:
                  - to: default
                    via: 10.0.0.1
                nameservers:
                  addresses: [192.168.16.53, 10.0.0.1]
        dest: /etc/netplan/01-static-ip.yaml
        owner: root
        mode: '0600'
      notify:
      - Apply netplan configuration
    - name: remove 50-cloud-init.yaml
      file:
        path: /etc/netplan/50-cloud-init.yaml
        state: absent
      notify:
      - Apply netplan configuration

    - name: Add NOPASSWD entry to sudoers file
      lineinfile:
        path: /etc/sudoers
        line: 'boboysdadda ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
    
    ## This is a workaround for the issue where the machine-id is the same for all the nodes when using clones in proxmox
    ## Could probably put some logic here to only run once, but I'm lazy
    # - name: Remove existing machine ID file
    #   file:
    #     path: /etc/machine-id
    #     state: absent
    #   notify: machine-id handler

    # - name: Remove other existing machine ID file
    #   file:
    #     path: /var/lib/dbus/machine-id
    #     state: absent
    #   notify: machine-id handler

  handlers:
  - name: Apply netplan configuration
    command: netplan apply
  - name: Restart resolvctl
    service:
      name: systemd-resolved
      state: restarted
  - name: Restart SSH Service
    service:
      name: ssh
      state: restarted
  - name: machine-id handler
    command: dbus-uuidgen --ensure
