---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: onepassword-token
  namespace: op-connect
spec:
  encryptedData:
    token: AgCI7Z7cvQ5Y7aafBlbKLPJ0dScq8JzHEmShS3efYvakUJ6TpMOR6q/ejbiRIMdmj/h9FM+F3rE8vg1hPoHmLEXZ/i2rQCJLQNqG/2vcZU25I4Bj9OEjItoUF+riNNuRqYopL0dEMcZ0ZwYhJhsV5bddTRaMB9XHDG5Idr0Y4rJ4bUvrDqpbmVpl0zQW/5G9c7D/HikPGg4vKDfnUzCVdgHqXjaKvjdFUd4odnlE8T178hRImv5+xCk+NgXrm7aKcbpXqkQFJfSQISno2vYkzVVW5X7ixmaZzbk31JKvGgCsbMmmXqcywZbCmvN7LwT1PDEO20p0TIEkeoL8sQKgkW4pkfnjwt1QJFOG5HuJ/sHrE936Z4SUJW6gAf09JqUOc9AvozxNSq7X+o61QowhS5hx89vR8MRId2HZY1eLVQQ4gItR/dbN2uE6A+/Xs+mkgYKqfluGZaqJ/vp9Tf/dMmATsLid1grwuUNTpL4hseWyAGtqDstttj1Og3FOtnJYKxJITwU68gsqIlab2vCfMVpAu6YZKFTgFwSqmixuTCv51ecTa84BCF0jIf37SBbYvbOEp+6W4rMHuulKjD95/Fk6RdOHNzyxJRzKpzY7MzkX7GNPFpA6t7VaKHvQl4VE8yRK0+SvQDpyiS9+28jwSE/OrnwzaW4X/JOaHmhJKPdYC2vYBTE2QNCclr5VRCEudA23ureVyzKltCLbBRUShTU1y51KuB7+mb4JXKXhSzDs/kBAM+2X8rr8GnZe/mS/kd9M47b/OEBQLfSDwwYGMzptcKBGS0KtQeo4MUeTy8cW55qLcscqTk0Pj2MHo1YIodNFqGVvZRcl08zljA0bKRMClHHEPLZ2fG3gehGfuo6A0D7LQx4qwk9p5/iAUDz2gl3YXF1tNq5KzUObs7gSfHDO9xw9cSRaVuWnF+oKFUN1zS5MZRwzS81DzPil2XqTTZ9Dv0k5lMUdH77RfAptBu5LTp/+BOfEZvF+TrzvrOjnaoN64oT4JfHpm5/8rI/UHN0rxAEU2csYw25depubR4JDlirF/AHRrE/17CEoMr4A85loYCslfcz8bRe8Y4qydieVzZbBEXs6n1LPMaojGotcxvYgBacqFZAC5G3Cpgp4CjBtZ+CjpvuGiodJ1IfgxHFeMHCmedKNl07iCivvOLlXNwSZsIEzKBBNfJ8LI7NijsMH+82YSxnvlfA3YQQYeSF8jQfJXLiXO3td/AtxVUk93CcQ+zQjQRG9uxu3Jt4Nf8hYU6GHvJTTiYbdRA23A6xen0YWORWbalUVNZWgDYLvUQjQKjvbJdh84D3d5/WxC2ep3tp812fm3foQWkFX8eWYFLyRuDFduiH6hNLYtZW2gSicUbvotnN/UHr2ptlBYFpwVXG1Ovs41VUTa9YRlNAn873qlthe59e9gBJHs9hJp2wZjnyuXrSHVHw+G5Pde+M33MpSVVpMA0P9c1dniax4fg/Ziykn0R4NJdX+QCTvOkUbMv4D79qOMx6Pe7L5DAFrotuCX/Ol2L/fnihC5+7cKXhkyku1ALIM/ctI1fjI5+qx
  template:
    metadata:
      creationTimestamp: null
      name: onepassword-token
      namespace: op-connect
