apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: onepassword-token
  namespace: op-connect
spec:
  encryptedData:
    token: AgC0LSfZeHBa+o8ulmc8E70zuiglREs/kIl6BO1MMRZeb1onn9kv0XKlZSyXWGXhlPp4iBhPysIGbw7bx3hfdh0IZDa9WFbNH7nNzciC/qh926m9QijD5Rum+kldATp+Yz7vWqsAo56o6HMPbUC3e/1p+83s+JCfLw1hBiEDyqM/a/5g8KSH4dw3/0i2dkx0vq1wpI8gyDxEd/husRniEtpb3UacoIBgj4ZxkiuFOL+aQHiOPg33v7LJflwQcogVWg6MPdg8E/2cMaeEC463bBYsiw7hJckiZAJ//kZ2PAkSYf7Z9+zIYbe+How9pcY0uAKanTmYRFASsY2MBWiymI4z5C8DtGkguZgKfUp6OMZjrmOXQQIu0Cd5HJgHa1iBxy+NN0wWmLZv2ATPqADYChB7BzQURUfMZQkP3NlzmQirKaeAjaHj4+FjBcjtIRaklxBOTsDX89n8PzrGo78VF9MpxvWK90+BsTWmsUiCAoNAahZAAQHIhNp/rnt35x7Y7EQw7NKji4TNocpgoHSzu9oBne3vF151dHDGQGz3Djgwr/45I5kp4yU4tsI/mMEKkTZwKL08sOWofDPAy70p7XdndSfgrVW5RzxdbCUSywFC8hwGBl9TGew0wcrivUH9mZJRsR+I++vq05ASPqMrP9cvNYt7vO5x2OLINJ428B3WSn9cg1JBqjxuBcwRGI6n6IupsMcx1nkqt3GKN8Otxlp6hujSAe3iGljSxTLSEsDOX+uXdjycvJZIcyPqcMxgD7J1pkxpd3KVCsM6LLjhFCTUs2jhBW0ypBe6GMFS9edAlnRYLgfaO+4Rp3GP73HcPYPicfcuXKZVMv3sHdUpYGU6IiaCB6DxLY0BxkAwezHkm3aNqvOS8yxQQdt0sZFpoCWKdVhVRZUUGZtl9TsaYHNXUoVIgGPsGIADZ0ETxkjQRdRfOTGxXUeLpuWWNjbaFqdSlAFiQZpSUP52xi03U3tc30phLSoJNZKIJnDn+fStYAWhRKPYNiYY6LdA7KRWvTtBvbeLM62fzczsPOCfPax+7W0f9qwLwKJ1j5x31M+Ibh/4z+FohsxxGpxPD84MOXX6zg73hqdpCE/KN6m6GindDwGz/Z4ONVDF+3LVFSid5Gk02iXCoGofpmlbW0viyF64obumUNUPkMnii46ySyBq/Ok8npqJZ6vgliDl85dH4b1DHan2sEREdb0foWcS9i7yXNnbbGBMn7r3ICzonhDkC0i5NTeuKmmZTvhB306CIx+u0K5j3sRO2RwdruMo7brMnC72a9ZiB+5oGx/4pNhyHt9JMGl2yy/rmClPhOA49crAFbBIUy95ROe6WER9hVIL9I+MLD9QfHPdhkE+YqMsE+J6Md8G0K1kqXmmwM8tImCTZFnhOTx02Z0ssJhcjYJC+SQjY81RJfVoPRng1JkmVuLbL21Oko0hB/oC12cjDpA5lNih4Wejg8yoAf7zE1N6PPUInZgMx7T1yUkopjK1NGNmJ0vBPgTp830muKzLI58GcL1lIEslkVFYmBkRjUv8q5NEtmlAEVqT6JGhTPVnk+ya
  template:
    metadata:
      creationTimestamp: null
      name: onepassword-token
      namespace: op-connect

