
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
        - name: code-server
          image: codercom/code-server:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: code-server-pvc
              mountPath: /home/coder
      volumes:
        - name: code-server-pvc
          persistentVolumeClaim:
            claimName: code-server-pvc
