namespace: code-server
labels:
  - pairs:
      'backstage.io/kubernetes-id': 'code-server'
      app: code-server
resources:
- namespace.yaml
- pv.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
