kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: code-server-pvc
  namespace: media
  labels:
    app: code-server
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: code-server-pv