apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k0smotron
  namespace: k0smotron
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git:secret:github.com-jamesatintegratnio-homelab/sshPrivateKey
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: infra
  source:
    repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
    targetRevision: HEAD
    path: clusters/management
  destination:
    server: https://kubernetes.default.svc
    namespace: k0smotron
  syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true