apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
    targetRevision: HEAD
    path: apps/nfs-subdir-external-provisioner
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-provisioner