apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: config-nfs-client
provisioner: k8s-sigs.io/config-nfs-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"