# patch_nfs_details.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: 10.0.0.10
            - name: NFS_PATH
              value: /mnt/user/kube_storage
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.0.0.10
            path: /mnt/user/kube_storage