apiVersion: v1
kind: Namespace
metadata:
  labels:
    backstage.io/kubernetes-id: op-connect-helm
  name: op-connect
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: onepassworditems.onepassword.com
spec:
  group: onepassword.com
  names:
    kind: OnePasswordItem
    listKind: OnePasswordItemList
    plural: onepassworditems
    singular: onepassworditem
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: OnePasswordItem is the Schema for the onepassworditems API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OnePasswordItemSpec defines the desired state of OnePasswordItem
            properties:
              itemPath:
                type: string
            type: object
          status:
            description: OnePasswordItemStatus defines the observed state of OnePasswordItem
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transit from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of job condition, Completed.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
            required:
            - conditions
            type: object
          type:
            description: 'Kubernetes secret type. More info: https://kubernetes.io/docs/concepts/configuration/secret/#secret-types'
            type: string
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: op-connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.15.0
  name: onepassword-connect-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: op-connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.15.0
  name: onepassword-connect-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - onepassword-connect-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - onepassword.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: op-connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.15.0
  name: onepassword-connect-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: onepassword-connect-operator
subjects:
- kind: ServiceAccount
  name: onepassword-connect-operator
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: connect
    app.kubernetes.io/instance: op-connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.15.0
  name: onepassword-connect
  namespace: default
spec:
  ports:
  - name: connect-sync
    port: 8081
  - name: connect-api
    port: 8080
  selector:
    app: onepassword-connect
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: connect
    app.kubernetes.io/instance: op-connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.15.0
  name: onepassword-connect
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onepassword-connect
  template:
    metadata:
      labels:
        app: onepassword-connect
        app.kubernetes.io/component: connect
        version: 1.7.2
    spec:
      containers:
      - env:
        - name: OP_SESSION
          valueFrom:
            secretKeyRef:
              key: 1password-credentials.json
              name: op-credentials
        - name: OP_BUS_PORT
          value: "11220"
        - name: OP_BUS_PEERS
          value: localhost:11221
        - name: OP_HTTP_PORT
          value: "8080"
        - name: OP_LOG_LEVEL
          value: info
        image: 1password/connect-api:1.7.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /heartbeat
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
        name: connect-api
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 999
          runAsUser: 999
        volumeMounts:
        - mountPath: /home/opuser/.op/data
          name: shared-data
      - env:
        - name: OP_HTTP_PORT
          value: "8081"
        - name: OP_SESSION
          valueFrom:
            secretKeyRef:
              key: 1password-credentials.json
              name: op-credentials
        - name: OP_BUS_PORT
          value: "11221"
        - name: OP_BUS_PEERS
          value: localhost:11220
        - name: OP_LOG_LEVEL
          value: info
        image: 1password/connect-sync:1.7.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /heartbeat
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
        name: connect-sync
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 15
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 999
          runAsUser: 999
        volumeMounts:
        - mountPath: /home/opuser/.op/data
          name: shared-data
      tolerations: []
      volumes:
      - emptyDir: {}
        name: shared-data
      - name: credentials
        secret:
          secretName: op-credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: op-connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.15.0
  name: onepassword-connect-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: onepassword-connect
  template:
    metadata:
      labels:
        app.kubernetes.io/component: operator
        name: onepassword-connect
    spec:
      containers:
      - args:
        - --zap-log-level=info
        command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          value: null
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: onepassword-connect-operator
        - name: OP_CONNECT_HOST
          value: http://onepassword-connect:8080
        - name: POLLING_INTERVAL
          value: "15"
        - name: OP_CONNECT_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: onepassword-token
        - name: AUTO_RESTART
          value: "true"
        image: 1password/onepassword-operator:1.8.1
        imagePullPolicy: IfNotPresent
        name: onepassword-connect
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          runAsGroup: 65532
          runAsUser: 65532
      serviceAccountName: onepassword-connect-operator
      tolerations: []
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-weight: "1"
  labels:
    app.kubernetes.io/instance: op-connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.15.0
  name: op-connect-health-check
  namespace: default
spec:
  containers:
  - command:
    - curl
    - http://onepassword-connect:8080/health
    image: curlimages/curl
    name: curl
  restartPolicy: Never
