---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd-image-updater
  title: ArgoCD Image Updater
  description: Some description of the argocd-image-updater component
spec:
  type: service
  lifecycle: homeprod
  owner: group:engineering
  system: argocd-system
  dependsOn:
    - component:default/argocd
