kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: calibre-books
  namespace: media
  labels:
    app: calibre
  annotations:
    nfs.io/storage-path: "calibre/calibre-books" # not required, depending on whether this annotation was shown in the storage class description
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi