apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: calibre
  namespace: media
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  ingressClassName: "nginx"
  rules:
  - host: calibre.cluster.arpa
    http:
      paths:
      - path: /
        backend:
          serviceName: calibre
          servicePort: 80