hajimari:
  resources:
    requests:
      cpu: 25m
      memory: 263M
    limits:
      cpu: 122m
      memory: 263M
  hajimari:
    instanceName: null
    defaultEnable: true
    namespaceSelector:
      matchNames:
        - default
        - downloads
        - media
        - monitoring
        - home-assistant
        - code-server
        - backstage
        - goldilocks
        - 
    name: You
    title: Management Cluster
    lightTheme: espresso
    darkTheme: espresso
    customThemes:
      - name: danger
        backgroundColor: '#0c0e0c'
        primaryColor: '#eaebea'
        accentColor: '#d8323c'
    showGreeting: false
    showAppGroups: true
    showAppUrls: false
    showAppInfo: true
    showAppStatus: true
    defaultAppIcon: mdi:application
    showBookmarkGroups: true
    showGlobalBookmarks: true
    alwaysTargetBlank: false
    defaultSearchProvider: DuckDuckGo
    searchProviders:
      - name: Google
        token: g
        icon: simple-icons:google
        searchUrl: https://www.google.com/search?q={query}
        url: https://www.google.com
      - name: DuckDuckGo
        token: d
        icon: simple-icons:duckduckgo
        searchUrl: https://duckduckgo.com/?q={query}
        url: https://duckduckgo.com
      - name: IMDB
        token: i
        icon: simple-icons:imdb
        searchUrl: https://www.imdb.com/find?q={query}
        url: https://www.imdb.com
      - name: Reddit
        token: r
        icon: simple-icons:reddit
        searchUrl: https://www.reddit.com/search?q={query}
        url: https://www.reddit.com
      - name: YouTube
        token: 'y'
        icon: simple-icons:youtube
        searchUrl: https://www.youtube.com/results?search_query={query}
        url: https://www.youtube.com
      - name: Spotify
        token: s
        icon: simple-icons:spotify
        searchUrl: hhttps://open.spotify.com/search/{query}
        url: https://open.spotify.com
    globalBookmarks:
      - group: Communicate
        bookmarks:
          - name: Discord
            url: 'https://discord.com'
          - name: Gmail
            url: 'http://gmail.com'
          - name: Slack
            url: 'https://slack.com/signin'
      - group: Cloud
        bookmarks:
          - name: Drive
            url: 'https://drive.google.com'
      - group: Dev
        bookmarks:
          - name: Codepen
            url: 'https://codepen.io/'
          - name: Devdocs
            url: 'https://devdocs.io'
          - name: Devhints
            url: 'https://devhints.io'
      - group: Media
        bookmarks:
          - name: Spotify
            url: 'http://browse.spotify.com'
          - name: Trakt
            url: 'http://trakt.tv'
          - name: YouTube
            url: 'https://youtube.com/feed/subscriptions'
      - group: Reading
        bookmarks:
          - name: Instapaper
            url: 'https://www.instapaper.com/u'
          - name: Reddit
            url: 'http://reddit.com'
      - group: Tech
        bookmarks:
          - name: TheNextWeb
            url: 'https://thenextweb.com/'
          - name: The Verge
            url: 'https://theverge.com/'
          - name: MIT Technology Review
            url: 'https://www.technologyreview.com/'
  service:
    selector:
      app.kubernetes.io/name: hajimari
      app.kubernetes.io/instance: in-cluster-hajimari
  ingress:
    main:
      enabled: true
      annotations:
        hajimari.io/enable: "false"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-url: |-
            http://authentik-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
        # If you're using domain-level auth, use the authentication URL instead of the application URL
        nginx.ingress.kubernetes.io/auth-signin: |-
            https://outpost.k8s.integratn.tech/outpost.goauthentik.io/start?rd=$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
      ingressClassName: "nginx"
      hosts:
        - host: k8s.integratn.tech
          paths:
            - path: /
              pathType: Prefix
      tls:
      - hosts:
        - k8s.integratn.tech
        secretName: hajimari-tls
  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: config-nfs-client