apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:

  name: infra-stack
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
        - clusters: {}
        - list:
            elements:

              - appName: op-connect-helm
                namespace: op-connect
                syncWave: 1
              - appName: external-secrets
                namespace: external-secrets
                syncWave: 1
              - appName: sealed-secrets
                namespace: kube-system
                syncWave: 1
              - appName: external-dns
                namespace: external-dns
                syncWave: 1
              - appName: metallb
                namespace: metallb-system
                syncWave: 1
              - appName: nfs-subdir-external-provisioner
                namespace: nfs-provisioner
                syncWave: 1

              - appName: cert-manager
                namespace: cert-manager
                syncWave: 2
              - appName: metrics
                namespace: kube-system
                syncWave: 2
              - appName: vertical-pod-autoscaler
                namespace: kube-system
                syncWave: 2
              
              - appName: ingress-nginx
                namespace: ingress-nginx
                syncWave: 3
              - appName: keycloak-crds
                namespace: keycloak
                syncWave: 3
              
              - appName: registry
                namespace: docker-registry
                syncWave: 4
              - appName: falco
                namespace: falco
                syncWave: 4
              - appName: goldilocks
                namespace: goldilocks
                syncWave: 4
              - appName: minio
                namespace: minio-tenant
                syncWave: 4
              - appName: keycloak
                namespace: keycloak
                syncWave: 4
              # - appName: kyverno
              #   namespace: kyverno
              #   syncWave: 4
  template:
    metadata:
      name: "{{.name}}-{{.appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
        argocd.argoproj.io/sync-wave: "{{.syncWave}}"
    spec:
      project: infra
      source:
        repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
        targetRevision: infra
        path: "core/{{.appName}}/overlays/{{.name}}"
      destination:
        name: in-cluster
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      destination:
        {{- if eq .childClusters true}}
        name: "{{.name}}"
        {{- else }}
        name: "in-cluster"
        {{- end }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          {{- if eq .syncPolicy "replace" }}
          - Replace=true
          {{- end }}