apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
labels:
  - pairs:
      'backstage.io/kubernetes-id': 'authentik'
resources:
- ../../base
- onePasswordItems.yaml
- ldap-outpost.yaml
- ./helm-all.yaml

