apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: forward_auth_outpost
    app.kubernetes.io/managed-by: goauthentik.io
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/version: 2024.4.2
  name: ldap-authentik-outpost
spec:
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: http
    - name: https
      port: 9443
      protocol: TCP
      targetPort: https
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: forward_auth_outpost
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: forward_auth_outpost
    app.kubernetes.io/managed-by: goauthentik.io
    app.kubernetes.io/version: 2024.4.2
  name: ldap-authentik-outpost
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: forward_auth_outpost
      app.kubernetes.io/managed-by: goauthentik.io
      app.kubernetes.io/name: authentik-proxy
      app.kubernetes.io/version: 2024.4.2
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: forward_auth_outpost
        app.kubernetes.io/managed-by: goauthentik.io
        app.kubernetes.io/name: authentik-proxy
        app.kubernetes.io/version: 2024.4.2
    spec:
      containers:
        - env:
            - name: AUTHENTIK_HOST
              valueFrom:
                secretKeyRef:
                  key: authentik_host
                  name: ldap-authentik-outpost-api
            - name: AUTHENTIK_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: ldap-authentik-outpost-api
            - name: AUTHENTIK_INSECURE
              valueFrom:
                secretKeyRef:
                  key: authentik_host_insecure
                  name: ldap-authentik-outpost-api
            - name: AUTHENTIK_HOST_BROWSER
              valueFrom:
                secretKeyRef:
                  key: authentik_host_browser
                  name: ldap-authentik-outpost-api
          image: ghcr.io/goauthentik/proxy
          name: proxy
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
            - containerPort: 9443
              name: https
              protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app.kubernetes.io/instance: forward_auth_outpost
    app.kubernetes.io/managed-by: goauthentik.io
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/version: 2024.4.2
  name: ldap-authentik-outpost
spec:
  ingressClassName: "nginx"
  rules:
    - host: ldap-outpost.k8s.integratn.tech
      http:
        paths:
          - backend:
              service:
                name: ldap-authentik-outpost
                port:
                  name: http
            path: /outpost.goauthentik.io
            pathType: Prefix
  tls:
    - hosts:
        - ldap-outpost.k8s.integratn.tech
      secretName: outpost-tls
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    app.kubernetes.io/instance: forward_auth_outpost
    app.kubernetes.io/managed-by: goauthentik.io
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/version: 2024.4.2
  name: ldap-authentik-outpost-api #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/homelab/items/ldap-authentik-outpost-api"