apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: authentik-postgres-credentials #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/homelab/items/authentik-postgres-credentials"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: authentik-redis-credentials #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/homelab/items/authentik-redis-credentials"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: authentik-secret-key #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/homelab/items/authentik-secret-key"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: authentik-email-credentials #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/homelab/items/no-reply-at-integratn-tech"