apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: authentik-postgres-credentials #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/homelab/items/authentik-postgres-credentials"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: authentik-redis-credentials #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/homelab/items/authentik-redis-credentials"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: authentik-secret-key #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/homelab/items/authentik-secret-key"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: authentik-email-credentials #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/homelab/items/no-reply-at-integratn-tech"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  app.kubernetes.io/instance: forward_auth_outpost
  app.kubernetes.io/managed-by: goauthentik.io
  app.kubernetes.io/name: authentik-proxy
  app.kubernetes.io/version: 2021.12.3
  name: authentik-outpost-api #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/homelab/items/authentik-outpost-api"