falco:
  falcosidekick:
    enabled: true
    config:
      existingSecret: falcosidekick
    webui:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/rewrite-target: /
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: falcosidekick.k8s.integratn.tech
            paths: 
            - path: /
        tls:
          - secretName: falcosidekick-tls
            hosts:
              - falcosidekick.k8s.integratn.tech
      redis:
        storageClass: data-nfs-client