falco:
  customRules:
    rules-custom.yaml: |-
      - macro: k8s_containers
        condition: >
          (k8s.ns.name = "argocd" and k8s.pod.name startswith "argocd")
  collectors:
    containerd:
      socket: /run/k0s/containerd.sock
    kubernetes:
      enabled: true
  falcosidekick:
    enabled: true
    config:
      # extraEnv:
      #   - name: DISCORD_WEBHOOKURL
      #     valueFrom:
      #       secretKeyRef:
      #         name: falcosidekick
      #         key: discord_webhookurl
    webui:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/rewrite-target: /
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: falcosidekick.k8s.integratn.tech
            paths: 
            - path: /
        tls:
          - secretName: falcosidekick-tls
            hosts:
              - falcosidekick.k8s.integratn.tech
      redis:
        storageClass: data-nfs-client