apiVersion: v1
kind: Service
metadata:
  name: mosquitto-mqtts
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: "home-assistant"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.1.201
  selector:
    app: mosquitto
  ports:
  - port: 1883
    targetPort: 1883