- op: replace
  path: /spec/template/spec/containers/name/external-dns/
  value:
   envFrom:
    - secretRef:
      name: pihole-password
    args:
    - --source=service
    - --source=ingress
    - --registry=noop

    - --policy=upsert-only
    - --provider=pihole
    - --pihole-server=http://192.168.16.53
