namespace: external-dns
resources:
- https://github.com/kubernetes-sigs/external-dns.git//kustomize
- namespace.yaml
patches:
- target: 
    group: apps
    version: v1
    kind: Deployment
    name: external-dns
  path: deployment_patch.yaml
