namespace: external-dns
resources:
- https://github.com/kubernetes-sigs/exteral-dns//kustomize
patches:
- target: apps
    version: v1
    kind: Deployment
    name: external-dns
  path: deployment_patch.yaml
