apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-sample-app
  namespace: argocd
  annotations: 
    # argocd-image-updater.argoproj.io/write-back-method: kustomization
    # argocd-image-updater.argoproj.io/git-branch: main
    # argocd-image-updater.argoproj.io/image-list: python-sample-app
spec:
  project: infra
  source:
    repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
    targetRevision: HEAD
    path: apps/python-sample-app
  destination:
    name: in-cluster
    namespace: python-sample-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true