apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-sample-app-pvc
spec:
  resources:
    requests:
      storage: 200m
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  volumeName: python-sample-app-pv