apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  annotations: 
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/jamesatintegratnio/backstage-backend:latest,app=ghcr.io/jamesatintegratnio/backstage-app:latest
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
    argocd-image-updater.argoproj.io/app.update-strategy: digest
spec:
  project: infra
  source:
    repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
    targetRevision: HEAD
    path: apps/backstage
  destination:
    name: in-cluster
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  revisionHistoryLimit: 3