apiVersion: v1
kind: ConfigMap

data:
  kustomize.buildOptions: --enable-helm
  accounts.backstage: apiKey
  accounts.image-updater: apiKey
  url: https://argocd.k8s.integratn.tech
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak-service.keycloak.svc.cluster.local:8443/realms/GoogleAuth
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
  
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/instance: argocd
  name: argocd-cm
  namespace: argocd