namespace: argocd
labels:
  - pairs:
      'backstage.io/kubernetes-id': 'argocd'
resources:
- namespace.yaml
<<<<<<< HEAD
- github.com/argoproj/argo-cd/manifests/cluster-install/?ref=v2.10.3
=======
- github.com/argoproj/argo-cd/manifests/cluster-install/?ref=v2.11.2
- github.com/argoproj/argo-workflows/manifests/cluster-install/?ref=v3.5.2
>>>>>>> 688c82b (upgrade argocd)
- ingress.yaml
- infra_project.yaml

components:
  - kustomized-helm-plugin

patches:
  - path: argocd-cm-patch.yaml
    target:
      labelSelector: "app.kubernetes.io/name=argocd-cm"
  
  - path: argocd-rbac-cm-patch.yaml
    target:
      labelSelector: "app.kubernetes.io/name=argocd-rbac-cm"
  
  - path: argo-server-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argo-server
    
  - path: argo-service-patch.yaml
    target:
      version: v1
      kind: Service
      name: argo-server

  - path: appset-controller-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-applicationset-controller

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
    - server.insecure="true"