apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring
resources: 
- ../../base
- ./helm-all.yaml
- datasources.yaml
- cred-onePasswordItem.yaml
- loki-promtail-dashboard.yaml
- ingress-nginx-dashboard.yaml
- media-dashboard.yaml
