apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak
labels:
  - pairs:
      'backstage.io/kubernetes-id': 'keycloak'
      app: keycloak
resources:
- namespace.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/24.0.3/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
- https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/24.0.3/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml

