all:
  hosts:
  # I know this looks dumb, but for some reason my router gives 
  # them all the same IP address and I can only address one at a time.
  # use `ansible-playbook -i hosts.yaml playbook.yaml --limit pi-cluster-1` to target a specific machine
  # as its the only way to make this work

    pi-cluster-1:
      ansiblehost: 10.1.42.180
      static_ip: 10.0.3.101
    pi-cluster-2:
      ansible_host: 10.1.42.180
      static_ip: 10.0.3.102
    pi-cluster-3:
      ansible_host: 10.1.42.180
      static_ip: 10.0.3.103
    pi-cluster-4:
      ansible_host: 10.1.42.180
      static_ip: 10.0.3.104
    pi-cluster-5:
      ansible_host: 10.1.42.180
      static_ip: 10.0.3.105
  vars:
    ansible_user: boboysdadda
    ansible_ssh_private_key_file: /home/boboysdadda/.ssh/id_ed25519
    ansible_become: yes
    ansible_become_method: sudo