all:
  hosts:
    pi-worker-1:
      ansible_host: 10.0.3.101
    pi-worker-2:
      ansible_host: 10.0.3.102
    pi-worker-3:
      ansible_host: 10.0.3.103
    pi-worker-4:
      ansible_host: 10.0.3.104
    pi-worker-5:
      ansible_host: 10.0.3.105
  vars:
    ansible_user: boboysdadda
    ansible_ssh_private_key_file: /home/boboysdadda/.ssh/id_ed25519
    ansible_become: yes
    ansible_become_method: sudo