---
- name: Update and upgrade packages
  hosts: all
  become: true

  tasks:
    # - name: Update and upgrade apt packages
    #   become: true
    #   apt:
    #     upgrade: yes
    #     update_cache: yes
    #     cache_valid_time: 86400 #One day
    - name: Enable root SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin yes'
        state: present

    - name: Restart SSH Service
      service:
        name: ssh
        state: restarted
    - name: Add public key to root SSH
      authorized_key:
        user: root
        key: "{{ lookup('file', '/home/boboysdadda/.ssh/id_ed25519.pub') }}"
        state: present