apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- ../../base
- ./all.yaml

patches:
- path: dnszones-patch.yaml
  target:
    group: cert-manager.io
    version: v1
    kind: ClusterIssuer
    name: letsencrypt-prod
