apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-argo-workflow-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: argo-workflow