apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      'backstage.io/kubernetes-id': 'argo-workflow'
resources:
- ../../base
- ./helm-all.yaml
- onePasswordItems.yaml
- admin-sa.yaml
- readonly-sa.yaml
- sa-tokens.yaml
- argoWorkflowTemplate.yaml
- argoWorkflow.yaml
- admin-sa-cluster-role-binding.yaml
- readonly-sa-cluster-role-binding.yaml
- executer-sa.yaml

# transformers:
#   - |-
#     apiVersion: builtin
#     kind: NamespaceTransformer
#     metadata:
#       name: argo-workflow-namespace-transformer
#       namespace: argo-workflow
#     setRoleBindingSubjects: none
#     unsetOnly: false
#     fieldSpecs:
#     - path: metadata/name
#       kind: Namespace
#       create: false

