apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-workflow
labels:
  - pairs:
      'backstage.io/kubernetes-id': 'argo-workflow'
resources:
- ../../base
- ./helm-all.yaml

