apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-stack
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - appName: argocd
          namespace: argocd
          pluginName: ""
        - appName: metallb
          namespace: metallb-system
        - appName: ingress-nginx
          namespace: ingress-nginx
        - appName: external-dns
          namespace: external-dns
        - appName: cert-manager
          namespace: cert-manager
          pluginName: kustomized-helm 
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: infra
      source:
        repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
        targetRevision: main
        path: "base/k8s/{{appName}}"
        plugin:
          name: {pluginName}
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true