apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-stack
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - appName: argocd
          namespace: argocd
        - appName: metallb
          namespace: metallb-system
        - appName: external-dns
          namespace: external-dns
        - appName: metrics
          namespace: kube-system
        - appName: nfs-subdir-external-provisioner
          namespace: nfs-provisioner
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: infra
      source:
        repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
        targetRevision: main
        path: "base/k8s/{{appName}}"
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true