apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-helm-stack
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - appName: cert-manager
          namespace: cert-manager
          helmReleaseName: cert-manager
          helmChartName: jetsack
          helmChartRepo: https://charts.jetstack.io
          path: overlays/k0s-homelab-cluster
        - appName: ingress-nginx
          namespace: ingress-nginx
          helmReleaseName: ingress-nginx
          helmChartName: ingress-nginx
          helmChartRepo: https://kubernetes.github.io/ingress-nginx
          path: ""
        - appName: external-secrets
          namespace: external-secrets
          helmReleaseName: external-secrets
          helmChartName: external-secrets
          helmChartRepo: https://charts.external-secrets.io
          path: ""
        - appName: op-connect-helm
          namespace: op-connect
          helmReleaseName: op-connect-operator
          helmChartName: onepassword-connect-operator
          helmChartRepo: https://1password.github.io/connect-helm-charts
          path: ""
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: infra
      source:
        repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
        targetRevision: main
        path: "base/k8s/{{appName}}/{{path}}"
        plugin:
          name: kustomized-helm
          env: 
            - name: HELM_RELEASE_NAME
              value: "{{helmReleaseName}}"
            - name: HELM_REPO_NAME
              value: "{{helmChartName}}"
            - name: HELM_REPO_URL
              value: "{{helmChartRepo}}"
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true