apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-helm-stack
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - appName: cert-manager
          namespace: cert-manager
        - appName: ingress-nginx
          namespace: ingress-nginx
        - appName: external-secrets
          namespace: external-secrets
        - appName: op-connect-helm
          namespace: op-connect
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: infra
      source:
        repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
        targetRevision: main
        path: "base/k8s/{{appName}}"
        plugin:
          name: kustomized-helm
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true