apiVersion: v1
kind: ConfigMap
metadata:
  name: daemon-json
  namespace: docker-registry
data:
  daemon.json: |
    {
      "insecure-registries" : ["localhost:5000", "registry.k8s.integratn.tech:5000"]
    }
