apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home-assistant-stack
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - appName: mosquitto-mqtt
      - appName: home-assistant
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: home-assistant
      source:
        repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
        targetRevision: main
        path: "apps/home-assistant/{{appName}}"
      destination:
        name: homelab
        namespace: home-assistant
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true