apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
labels:
  - pairs:
      'backstage.io/kubernetes-id': 'cert-manager'
      'test-label': 'test-label-value'
resources:
- namespace.yaml
- https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.crds.yaml
- issuer.yaml
- onepassword-item.yaml
