apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
labels:
  - pairs:
      'backstage.io/kubernetes-id': 'cert-manager'
      'test-label': 'test-label-value'
resources:
- namespace.yaml
- onepassword-item.yaml
