apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-api-key #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/homelab/items/cloudflare-api-key"