apiVersion: v1
kind: Namespace
metadata:
  labels:
    backstage.io/kubernetes-id: op-connect-helm
  name: op-connect
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: op-connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.15.0
  name: onepassword-connect-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: op-connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.15.0
  name: onepassword-connect-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - onepassword-connect-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - onepassword.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: op-connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.15.0
  name: onepassword-connect-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: onepassword-connect-operator
subjects:
- kind: ServiceAccount
  name: onepassword-connect-operator
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: connect
    app.kubernetes.io/instance: op-connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.15.0
  name: onepassword-connect
  namespace: default
spec:
  ports:
  - name: connect-sync
    port: 8081
  - name: connect-api
    port: 8080
  selector:
    app: onepassword-connect
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: connect
    app.kubernetes.io/instance: op-connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.15.0
  name: onepassword-connect
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onepassword-connect
  template:
    metadata:
      labels:
        app: onepassword-connect
        app.kubernetes.io/component: connect
        version: 1.7.2
    spec:
      containers:
      - env:
        - name: OP_SESSION
          valueFrom:
            secretKeyRef:
              key: 1password-credentials.json
              name: op-credentials
        - name: OP_BUS_PORT
          value: "11220"
        - name: OP_BUS_PEERS
          value: localhost:11221
        - name: OP_HTTP_PORT
          value: "8080"
        - name: OP_LOG_LEVEL
          value: info
        image: 1password/connect-api:1.7.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /heartbeat
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
        name: connect-api
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 999
          runAsUser: 999
        volumeMounts:
        - mountPath: /home/opuser/.op/data
          name: shared-data
      - env:
        - name: OP_HTTP_PORT
          value: "8081"
        - name: OP_SESSION
          valueFrom:
            secretKeyRef:
              key: 1password-credentials.json
              name: op-credentials
        - name: OP_BUS_PORT
          value: "11221"
        - name: OP_BUS_PEERS
          value: localhost:11220
        - name: OP_LOG_LEVEL
          value: info
        image: 1password/connect-sync:1.7.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /heartbeat
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
        name: connect-sync
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 15
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 999
          runAsUser: 999
        volumeMounts:
        - mountPath: /home/opuser/.op/data
          name: shared-data
      tolerations: []
      volumes:
      - emptyDir: {}
        name: shared-data
      - name: credentials
        secret:
          secretName: op-credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: op-connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.15.0
  name: onepassword-connect-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: onepassword-connect
  template:
    metadata:
      labels:
        app.kubernetes.io/component: operator
        name: onepassword-connect
    spec:
      containers:
      - args:
        - --zap-log-level=info
        command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          value: null
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: onepassword-connect-operator
        - name: OP_CONNECT_HOST
          value: http://onepassword-connect:8080
        - name: POLLING_INTERVAL
          value: "15"
        - name: OP_CONNECT_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: onepassword-token
        - name: AUTO_RESTART
          value: "true"
        image: 1password/onepassword-operator:1.8.1
        imagePullPolicy: IfNotPresent
        name: onepassword-connect
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          runAsGroup: 65532
          runAsUser: 65532
      serviceAccountName: onepassword-connect-operator
      tolerations: []
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  labels:
    backstage.io/kubernetes-id: op-connect-helm
  name: onepassword-token
  namespace: op-connect
spec:
  encryptedData:
    token: AgA5ts6xF1T0Z4KE3kEmue2nWCJN7pt86K/PI3H9ZVBHtdNpjdiglZ9YHuFsp35cjyeYfZH7WBdEP0eXe0RK/sdzndv1eoyg/ZGTbAaCdij/gL4ayZOuedwpFWyz98R5wrU/2CCSSD72QFhD6zn2ZVhqoj67bggZjyICkfERjFX4TFFYflpUQHvUvinRoC+24ie2xm+dzyYKQYz3zf+eLuizNd60kgrbeWIS8yjBJdDACoVc/ake+NAziydqKoyXiQYSzPI7pqvhfjGrxuyhVz3yGdjoh8AybY5Dtdamm5MPUP/BALrearspTeTye9nSOti9mQ+Y5KEdVN1WvC2A01DmYBB8ovOeeBjgjQzDd7U2uhIfpvqmunDHfAdaVbZsmjW9ZngiU/Z140mIM1Sz1g4BcOm0ZFdexH4r70JLmhpfv9x4UnL+m6PlT388fB6o1hzNRn07/GWOuM65vXAY4KWzOjlo2BMrfIZWdEyfbNiki0kksBMDNmZviv/Cuv8L0YdZzWVWiJ/beK8UjPeBtzW6Liggdc+BfoC9T9a9tPujGLeWnR5siwAd2HTzfPrv1pJ2CrYHUqAhJkVE992ddegf9LSxUkmzRErzdU3Euvh9JFwesZqq+EGKfYdUHqJynJIUHwRsLgeHtyQd3DBvDGOk8eVBGluwTboWVrky9LG5s4ntkOrdOMNN0Z8oQy/V9PZz72VyPA+RWIj8gOuFv4+dRdd4hQqv4qkXWm49sOHAkGHaagnNg0P0PmyyYJ3VBzA3letIWcS2d3Dh9Hv4OrF+HrLGn8RmYoMq2Hl8L8M0R+CKjUnHnBVBVYYEYEeJZWoLgBxft6ZemDqqqGm1VSamXesxDzazu7XaCNvr/mKlTCjKVVC7eoGAXedlVOvDnZTTxPcuoZ57txXP3peVRN5BD6sHg++g2Ky7E+Ynx6OvmflUPPojbktxSsw0yO0gHqbRQBdxLtXAKyo2KFoXLKTYPbe51xDtTUL1gGk+ApNVnCR/Qocb8Q6SlK/fPGsrqvuwVosKOrEnZhI/ZTr1olH+hru3oUaWmIRUEfKzfBogcKhp1UQlErLG7WgCGRa7x/oqNl70CAth0nOTVprLG/Qz9fD7MV7lWhODf1m1IVZGpMI+jjyoruJRqXVAS/80TH5FDuK4LCIgOEqgGyoNyv0e5ovCiCN55Ao8IvjO6D4XSiZX7wU3hokQjItI8odzaYWIGW8ZuByA1l7oSsT/70+z1U9tCli1d6BkzEIGcnQdrncuZPoTkSDbHeSywEvQaie5ui0dSWsXU70u8ldSpPvbtfu4AQbz+KhCXLLBeU/KnDAx0C68tSI4svE//NflFbXMs/iHriYSGer3gwTEw5xF0hSjzr7H/ypaRYRC1RtHbACKcSO69CevrfWGcisBYFBPV3HCr8F35VUUKHdheO69O9jeEl3sgUPzmR4enYgb9AG+Sea9bWIFnkm9FriGfkGLkPw1oDoXFcQbGgbQLrkXordWnBGWuvtLqkOERdKrnySoX8v52jhCEsaAJ/SBc7iK0EbcdIhcLydmPZWRV+P9aO4=
  template:
    metadata:
      creationTimestamp: null
      name: onepassword-token
      namespace: op-connect
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  labels:
    backstage.io/kubernetes-id: op-connect-helm
  name: op-credentials
  namespace: op-connect
spec:
  encryptedData:
    1password-credentials.json: AgBQ5o60xCQ7kZ8yszIyyKbsYfjmuEWUiFWlU6/2+y6vIKHAx4zfMRV5gmwvrlrDE3C4Zpbl3R8iBLqwAa7LeQRB9Gsc+UWbXmreEH0sWPTtuUXfQ6M5FrqjpDbabcRIpwSFt6lRGxsnGz7hvVYy/ijJRelMod4gZY53++HBVM+vqNLIKB/XTFnNzaFTJN7hn2NU8ETjppO9oBZ+Q6BtJoSSdRNX2VZtElV8M3F9OCedAvYLIwMzUtD2Ir8w1SD2ImXSY9wtYYAlprTqrDGtDl1y5ia4DCK790IOYirXCw1GYJdBGDzfFjI7Sz0CwkL6s8dMyK5n1SJIsU2cvQWmdc7ravjiDQZU5cLZlg1foOx05M4TX/KE7Sk1WVw4/DymEdGa6gPYOhdSbPCaXwIIMEyqh5Xnfa0hyEZAqnubZr0fn4tgB+z+n8P5+aR+p+0TvnzvYQta+YfonWImP5kIwPLxvN0//F/cQyoW5uVkpsYmIvDF7y8jnNVuy8+bwhSprzQdYWY2E5/bKwvsiaBhlkSTCEypUps+pL3gtNeAc24HECYfBtDaXcf4KbFoa/w08Vro3JKhB8X4jFU4Sh4rcABd1Gg55Kc2UzGiZUUgEJL2yH1dsw/+CDn2D6sf5msmWuestrOL4zsWxs/FBqNjlGqh38dpr/1ajdzSfngZ2Peqro45wapcdIpSiTbyTKHgzmauWOpnerLppoHHsYI87J6yfqaSumGV7FakZbqzrTxkr2syHcEqY9/FbBULEtadBo2EfAzhQhTUmZWPBZ/26hkuDt/2SzleKo5pXMmWyFHL69h7vuvt2ri38MJz+WXZnBbQ5LEDhsyvj4w2BhYfxRMGDwc0PEU49NrYz9GnlyNvYoVTo1kPiN/J3mgGZb8oqjSeY82CLaBEqzfG4SkNU0Q/mzLLXUneJGEi9dbRzL4FYmzEG5rwSo/i4kblOKJUlY5TsQSTrVSmvXKQ8KSpJPy8FFR99rOVLZSgc+/L4DrTjVcScSdtIXoS6IBypVMXPAL6rjly0szUe4D7gCAKGIuNur/DJzyRMN0EHhwbsSD0I9m6x1Hft3qQXq6KoKw1BjnY29NDqIYiVNk6pQO5imU8elsWMHHh0NgbqM+kUgpfSKzQRwIxjiUTfiXKR7CUtzUU5+qsvXKIGq9wZVPX2eWapSk6dsGKERHMuy+WAzCDnLPjk1ArvDRRGJiPbVXfQyGJmxwjLy83lH6AglyL+1pn+k00SXuQiHFw7jHc6mI2UpyHgiJK/Z4XpLZAc31JtmvznL+/z/8p+M/+ZZwB7epjvQtoqxOdU0iFluJBLefN0sDFlTkcqAij6Ff8Bunj1WF9XIrWpoXi8hAYTt7AlSYW/Mxa/fV7qo6Lssvq/weJY9WoIhdH2k/IL/fNDb79Gay4vh/+jq1SgTWjMxR+HMiUxvJU4d4/q4c6BdC+0BZCRsm4tVKTA1VwJp6y+HO4h1pMG7J3McMwMzLxZFqCKRyX0C9x8Tba3vDxgd1CxNWVS/Or8JqEW59e8DcxLX0C5tTfgz0z71PbkmiNUjH0G9zPBOE8OiosVV89nXG5GfacWE0HVm4/fnUKnygd+IIgjWzCsz52nBYEA7m6++xh3rAvf7LPdOO16h90miCoSL8JvLNrtzD6TFVyxqz4iugEAZZhNT2dhtFlZVrxogHuLyOEvlI6viKjRCD2YuE9aolbmfB/pFqYB96M+T+IlMeXFZxSukAPohS3fyOOtEOzNitk+/Yx5Wz2D8HtsQdrJ6ZHVWUboJN4LrE66z5PW45rNRilysRy6LJg4RYpBqDqL5ghH7JavNqz0pc7a3fFf0qvhWZacr4b3DvvrJPqJbgmMt5nGA3c6PwMb1WtvLwyXeJWfI1W2gn5Vwm6KrLjmw3U4J412Cqr1D7YXxsjHrGlZ2HT0XVhCWiU/Efq68qmOblwgAQEGQB4sV07vPv+ZpDDQ3qmvccqORdoLZdjoykz+caojAeCDIRI40/TIkFAKi+c4iNEU0iRibezV3ln20RuFfFVz0ZAGOhc48uj+jZ0MtzUNNODF/PJTc2Fkuc7qEKBOXk5cT2/rQIdK2EabhtNt2xHYUGPYV2/XqCc8PJ5WIggf99iZ+h4Cjc5VPTtTD4u72yoQRQNVw9uU2vpObYBMMYmSJvyEGDrbfdlf4hU+kWMTxVkE1MNxDt9HnHzLhB+Q0s/1gZ9oyl2XpqSEZyW/gNyj0TMMMWZD4D44lTlbpWl/SgaUFp7ixPaY/sY+vetZ9wF6kxs6n2epf8BoUObOg+ukAL6ksh0Kr480OWXuFInNkFA6BZ88bm5w7j4zwy0xZkYKP8iPL5BnELWeYQcaunuIvKKU1lLLxAWseOttijw7vR9qDifDZGRqv4kMF62MFlR3srOufCBsjr4Huleq6i1KKCBMWi9oKH42c6LgNBoPa/IJeKn6wa+kaPxPSb8lrWWRTI6f9Z2h7AFQb3PAFoWDYx5sgQyOWaX1YDnkNggIXmAMUpI8vdFrOD7WNpUgcry9IkJlPmN3lVmQ4ETzsV2/C5KdxQ7hn+hnzyfwUUVYNUOG255TdEF0jARESKU6c3R1E8pm7zyXBCbqzmK5FPO3z+9UrspJHkVo7CvTZRrs9AbAGu2aUxOXiY=
  template:
    metadata:
      creationTimestamp: null
      name: op-credentials
      namespace: op-connect
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-weight: "1"
  labels:
    app.kubernetes.io/instance: op-connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.15.0
  name: op-connect-health-check
  namespace: default
spec:
  containers:
  - command:
    - curl
    - http://onepassword-connect:8080/health
    image: curlimages/curl
    name: curl
  restartPolicy: Never
