apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  selector:
      matchLabels:
        app.kubernetes.io/name: argocd-repo-server
  template:
    spec:
      containers:
      - name: kustomized-helm
        command: [/var/run/argocd/argocd-cmp-server] # Entrypoint should be Argo CD lightweight CMP server i.e. argocd-cmp-server
        # image: busybox # This can be off-the-shelf or custom-built image
        image: quay.io/argoproj/argocd:v2.10.3
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: plugin.yaml
            name: helm-kustomize-plugin-config

          - mountPath: /var/run/argocd/helm-kustomize-plugin/generate.sh
            subPath: generate.sh
            name: helm-kustomize-plugin-config

          - mountPath: /var/run/argocd/helm-kustomize-plugin/init.sh
            subPath: init.sh
            name: helm-kustomize-plugin-config
          # Starting with v2.4, do NOT mount the same tmp volume as the repo-server container. The filesystem separation helps 
          # mitigate path traversal attacks.
          - mountPath: /tmp
            name: cmp-tmp
      volumes:
        - configMap:
            name: helm-kustomize-plugin-config
          name: helm-kustomize-plugin-config
        - emptyDir: {}
          name: cmp-tmp