apiVersion: batch/v1
kind: CronJob
metadata:
  name: plex-media-manager
  namespace: media
spec:
  schedule: "20 22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          initContainers:
            - name: render-dynamic-config-tv
              image: chrisjohnson00/jinja-init:v1.0.0
              env:
                # source and destination files
                - name: JINJA_SRC_FILE
                  value: /config_src/config.yaml
                - name: JINJA_DEST_FILE
                  value: /config/config.yaml
                # let's be verbose
                - name: VERBOSE
                  value: "1"
                - name: JINJA_VAR_plex_api
                  value: /secrets
                - name: JINJA_VAR_plex_url
                  value: /secrets
                - name: JINJA_VAR_sonarr_api
                  value: /secrets
                - name: JINJA_VAR_sonarr_url
                  value: /secrets
                - name: JINJA_VAR_radarr_api
                  value: /secrets
                - name: JINJA_VAR_radarr_url
                  value: /secrets
                - name: JINJA_VAR_tmdb_api
                  value: /secrets
              volumeMounts:
                # configMap mount point
                - name: pmm-config-template
                  mountPath: /config_src
                # target directory mount point; the final config file will be created here
                - name: config
                  mountPath: /config
                - name: secrets
                  mountPath: /secrets
          containers:
            - name: plex-media-manager
              image: meisnate12/plex-meta-manager:latest
              imagePullPolicy: Always
              args: [ "--run", "--read-only-config" ]
              resources:
                limits:
                  cpu: 100m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 125Mi
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: tv-config
                  mountPath: /config/tv.yaml
                  subPath: tv.yaml
                - name: movie-config
                  mountPath: /config/movies.yaml
                  subPath: movies.yaml
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: pmm-config-pvc
            - configMap:
                name: pmm-config-template
              name: pmm-config-template
            - configMap:
                name: movies-config
              name: movie-config
            - configMap:
                name: tv-config
              name: tv-config
            - name: secrets
              secret:
                secretName: pmm-secrets
          restartPolicy: OnFailure