apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: plex-api-secret #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/homelab/items/plex-api-key"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: radarr-api-secret #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/homelab/items/radarr-api-key"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sonarr-api-secret #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/homelab/items/sonarr-api-key"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: tmbd-api-secret #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/homelab/items/tmdb-api-key"