## This file is a template remove the .template to use the file
apiVersion: v1
kind: ConfigMap
metadata:
  name: pmm-config-template
data:
  config.yaml: |
    libraries:                                      # Library mappings must have a colon (:) placed after them
      Movies:
        metadata_path:
        - file: config/movies.yaml
        - git: meisnate12/MovieCharts
        - git: meisnate12/Studios
      TV Shows:
        metadata_path:
        - file: config/tv.yaml
        - git: meisnate12/Networks
      Kids TV Shows:
        metadata_path:
        - file: config/tv.yaml
        - git: meisnate12/Networks
      # Anime:
      #   metadata_path:
      #   - git: meisnate12/AnimeCharts
      #   - file: ./config/config/anime.yml
    settings:                                       # Can be individually specified per library as well
      cache: true
      cache_expiration: 60
      asset_directory: config/assets
      asset_folders: true
      create_asset_folders: true
      assets_for_all: false
      sync_mode: append
      show_unmanaged: true
      show_filtered: false
      show_missing: true
      save_missing: true
      run_again_delay: 2
      missing_only_released: false
      delete_below_minimum: false
      tvdb_language: default
      show_missing_assets: true
      show_missing_season_assets: false
      delete_not_scheduled: false
      only_filter_missing: false
      ignore_ids:
      ignore_imdb_ids:
      asset_depth: 0
      dimensional_asset_rename: false
      show_options: false
      minimum_items: 3
      download_url_assets: false
      default_collection_order:
      verify_ssl: true
      playlist_sync_to_users: all
      show_missing_episode_assets: false
      show_asset_not_needed: true
      item_refresh_delay: 0
      custom_repo:
      prioritize_assets: false
      playlist_report: true
      check_nightly: false
      show_unconfigured: true
      playlist_exclude_users:
    plex:                                           # Can be individually specified per library as well
      url: '{{ plex_url }}'
      token: '{{ plex_api }}'
      timeout: 60
      clean_bundles: false
      empty_trash: false
      optimize: false
    tmdb:
      apikey: '{{ tmdb_api }}'
      language: en
      cache_expiration: 60
      region:
    # tautulli:                                       # Can be individually specified per library as well
    #   url: http://plex_host:8181/tautulli
    #   apikey: 
    # anidb:          # Optional
    #   username: your_account
    #   password: your_pass
    #   language: en
    #   client:
    radarr:                                         # Can be individually specified per library as well
      url: '{{ radarr_url }}'
      token: '{{ radarr_api }}'
      version: v3
      root_folder_path: /data/media/movies
      monitor: true
      availability: announced
      quality_profile: HD - 720p/1080p
      # tag:
      search: false
      add_existing: false
      radarr_path:
      plex_path:
      add_missing: false
      upgrade_existing: false
      ignore_cache: false
    sonarr:                                         # Can be individually specified per library as well
      url: '{{ sonarr_url }}'
      token: '{{ sonarr_api }}'
      version: v3
      root_folder_path: /data/media/tv
      monitor: all
      quality_profile: HD - 720p/1080p
      language_profile: English
      series_type: standard
      season_folder: true
      # tag:
      search: false
      cutoff_search: false
      add_existing: false
      sonarr_path:
      plex_path:
      add_missing: false
      upgrade_existing: false
      ignore_cache: false
    trakt:
      client_id: '{{ trakt_client_key }}'
      client_secret: '{{ tract_client-secret }}'
      authorization:
        access_token: '{{ tract_access_token }}'
        token_type: Bearer
        expires_in: 7889237
        refresh_token: '{{ tract_refresh_token }}'
        scope: public
        created_at: 1692893834
      pin: {{ trakt_pin }}
    # #My Anime List
    # mal:
    #   client_id: your_client_id
    #   client_secret: your_secret
    #   authorization:
    #     access_token: your_access_token
    #     token_type: Bearer
    #     expires_in: 123123123
    #     refresh_token: your_refresh
    #   localhost_url:
    #   cache_expiration: 60
