apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: k8s-sigs.io/nfs-subdir-external-provisioner
  name: pmm-config-pv
  labels:
    app: plex-media-manager
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    path: /mnt/user/kube_storage/pmm
    server: 10.0.0.12
  persistentVolumeReclaimPolicy: Retain
  storageClassName: data-nfs-client
  volumeMode: Filesystem
status: