kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pmm-config-pvc
  namespace: media
  labels:
    app: plex-media-manager
spec:
  storageClassName: data-nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pmm-config-pv