apiVersion: v1
kind: ConfigMap
metadata:
  name: tv-config
data:
  tv.yaml: |
    ######################################################
    #                Chart Collections                   #
    ######################################################
    templates:
        Chart:
            sort_title: +1_<<num>><<collection_name>>
            sync_mode: sync
            smart_label: random
        network:
            optional:
                - network
            tmdb_network: <<network>>
            url_poster: <<poster>>
            sort_title: +2_<<collection_name>>
            sync_mode: sync
    collections:
      Plex Popular:
        template: { name: Chart, num: 1 }
        tautulli_popular:
          list_days: 30
          list_size: 20
          list_buffer: 20
        tautulli_watched:
          list_days: 30
          list_size: 20
          list_buffer: 20
        summary: Shows Popular on Plex
      Trending Shows:
        template: { name: Chart, num: 2 }
        trakt_trending: 30
        tmdb_trending_daily: 10
        tmdb_trending_weekly: 10
        summary: Shows Trending across the internet
      Popular Shows:
        template: { name: Chart, num: 3 }
        tmdb_popular: 40
        imdb_list:
          url: https://www.imdb.com/search/title/?title_type=tv_series,tv_miniseries
          limit: 40
        summary: Popular Shows across the internet
      Top Rated:
        template: { name: Chart, num: 4 }
        imdb_list:
          url: https://www.imdb.com/search/title/?title_type=tv_series,tv_miniseries&num_votes=20000,&sort=user_rating,desc
          limit: 100
        tmdb_top_rated: 100
        summary: Top Rated Movies across the internet
      Emmy Winners:
        template: { name: Chart, num: 5 }
        imdb_list: https://www.imdb.com/search/title/?title_type=tv_series,tv_miniseries&groups=emmy_winner
        summary: Emmy Winning Shows
      Best New Shows of 2021:
        template: { name: Chart, num: 6 }
        imdb_list:
          url: https://www.imdb.com/search/title/?title_type=tv_series,tv_miniseries&release_date=2021-01-01,2021-12-31&user_rating=7.0,&num_votes=150,&sort=num_votes,desc
          limit: 50
        summary: Best New Shows of 2021
      Best New Shows of 2022:
        template: { name: Chart, num: 7 }
        imdb_list:
          url: https://www.imdb.com/search/title/?title_type=tv_series,tv_miniseries&release_date=2022-01-01,2022-12-31&user_rating=7.0,&num_votes=150,&sort=num_votes,desc
          limit: 50
        summary: Best New Shows of 2022
      Best New Shows of 2023:
        template: { name: Chart, num: 8 }
        imdb_list:
          url: https://www.imdb.com/search/title/?title_type=tv_series,tv_miniseries&release_date=2023-01-01,2023-12-31&user_rating=7.0,&num_votes=150,&sort=num_votes,desc
          limit: 50
        summary: Best New Shows of 2023
      Cartoon Network:
        template: { name: network, network: "56, 217, 1232, 1483, 2193, 3917, 4771", poster: https://theposterdb.com/api/assets/172187}
      Adult Swim:
        template: { name: network, network: 80, poster: https://theposterdb.com/api/assets/98825}
