apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-stack
spec:
  generators:
  - list:
      elements:
      - appName: oauth2-proxy
        namespace: kube-system
      - appName: sealed-secrets
        namespace: kube-system

  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: homelab
      source:
        repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
        targetRevision: main
        path: "apps/{{appName}}"
      destination:
        name: homelab
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true