apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:

  name: apps-stack
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - matrix:
      generators:
        - clusters: {}
        - git: 
            repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
            revision: main
            files:
              - path: "apps/**/config.json"
  template:
    metadata:
      name: "{{.name}}-{{.path.basename}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: "{{.project}}"
      source:
        repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
        targetRevision: apps
        path: "apps/{{.path.basename}}/overlays/{{.name}}"
      destination:
        name: "{{.name}}"
        namespace: "{{.cluster.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 3
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 10m
        managedNamespaceMetadata:
          labels:
            goldilocks.fairwinds.com/enabled: "true"  
