apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:

  name: apps-stack
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
        - clusters: {}
        - list:
            elements:
              - appName: backstage
                namespace: backstage
                project: infra
              - appName: hajimari
                namespace: hajimari
                project: infra
              - appName: plex-metadata-manager
                namespace: pmm
                project: media
              - appName: python-sample-app
                namespace: python-sample-app
                project: infra
             
  template:
    metadata:
      name: "{{.name}}-{{.appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: "{{.project}}"
      source:
        repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
        targetRevision: apps
        path: "apps/{{.appName}}/overlays/{{.name}}"
      destination:
        name: in-cluster
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            goldilocks.fairwinds.com/enabled: "true"  
  templatePatch: |
    spec:
      destination:
        {{- if eq .childClusters true}}
        name: "{{.name}}"
        {{- else }}
        name: "in-cluster"
        {{- end }}
