ingress-nginx:
  controller:
    publishService:
      enabled: true
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 10.0.2.200
        metallb.universe.tf/address-pool: default
    allowSnippetAnnotations: true