apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 3
  db:
    vendor: postgres
    host: 10.0.3.1
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: credential
  ingress:
    # className: "nginx"
    # annotations:
    #   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #   nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  http:
    tlsSecret: keycloak-tls
  hostname:
    hostname: keycloak.k8s.integratn.tech
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
  # unsupported:
  #   podTemplate:
  #     spec:
  #       containers:
  #         - name: keycloak
  #           args: 
  #             - '-Djgroups.dns.query=keycloak-discovery.keycloak'
  #             - '--verbose'
  #             - start-dev 