---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    operator.min.io/authors: MinIO, Inc.
    operator.min.io/license: AGPLv3
    operator.min.io/support: https://subnet.min.io
  name: console-sa
  namespace: minio-operator
