namespace: minio-tenant
labels:
  - pairs:
      'backstage.io/kubernetes-id': 'minio-tenant'
resources: 
- github.com/minio/operator?ref=v5.0.15
- storage-user-onePasswordItem.yaml
- ingress.yaml
- tenant.yaml


patches:
  # patch console service to load balance
  - path: console-service-patch.yaml
    target:
      version: v1
      kind: Service
      name: console

# Setup DirectPV https://github.com/minio/directpv/blob/master/docs/installation.md