namespace: minio-tenant
labels:
  - pairs:
      'backstage.io/kubernetes-id': 'minio-tenant'
resources: 
- storage-user-onePasswordItem.yaml
- ingress.yaml
- tenant.yaml
# - minio-operator.yaml
# - minio-operator-role.yaml
# - minio-operator-binding.yaml
# - tenants.minio.min.io.yaml
# - policybindings.sts.min.io.yaml
# - miniojobs.job.min.io.yaml
# - operator.yaml
# - sts.yaml
# - console-sa.yaml
# - console-sa-secret.yaml
# - console-sa-role.yaml
# - console-sa-binding.yaml
# - console-env.yaml
# - console.yaml
