
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
        - name: code-server
          image: ghcr.io/jamesatintegratnio/code-server:main
          env:
            - name: PUID
              value: "99"
            - name: PGID
              value: "100"
            - name: "TZ"
              value: "America/Denver"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: code-server-pvc
              mountPath: /home/coder
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1500m
              memory: 2048Mi
      volumes:
        - name: code-server-pvc
          persistentVolumeClaim:
            claimName: code-server-pvc


