
helmCharts:
- name: grafana
  releaseName: grafana
  namespace: monitoring
  valuesInLine:
    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
  repo: https://grafana.github.io/helm-charts
  version: 6.57.4
