apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: backstage-secrets #this name will also be used for naming the generated kubernetes secret
  labels:
        argocd.argoproj.io/secret-type: backstage-secrets
        app: backstage
  namespace: backstage
spec:
  itemPath: "vaults/homelab/items/backstage-secrets"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: backstage-org-yaml #this name will also be used for naming the generated kubernetes secret
  labels:
        argocd.argoproj.io/secret-type: backstage-secrets
  namespace: backstage
spec:
  itemPath: "vaults/homelab/items/backstage-org-yaml"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: backstage-app-config #this name will also be used for naming the generated kubernetes secret
  labels:
        argocd.argoproj.io/secret-type: backstage-secrets
  namespace: backstage
spec:
  itemPath: "vaults/homelab/items/backstage-app-config"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: backstage-frontend-secrets #this name will also be used for naming the generated kubernetes secret
  labels:
        argocd.argoproj.io/secret-type: backstage-secrets
        app: backstage
  namespace: backstage
spec:
  itemPath: "vaults/homelab/items/backstage-frontend-secrets"
