apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: github.com-jamesatintegratnio-homelab #this name will also be used for naming the generated kubernetes secret
  labels:
        argocd.argoproj.io/secret-type: backstage-secrets
  namespace: backstage
spec:
  itemPath: "vaults/homelab/items/backstage-secrets"