apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: Website
      url: https://backstage.k8s.integratn.tech
  annotations:
    github.com/project-slug: jamesAtIntegratnIO/backstage-demo
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-namespace: backstage
    backstage.io/kubernetes-label-selector: app=backstage
    argocd/app-name: backstage
spec:
  type: service
  owner: user:guest
  lifecycle: experimental