---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage-manifests
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: service
      url: https://backstage.k8s.integratn.tech
      icon: argocd
    - title: Manifests
      url: https://github.com/jamesatintegratnio/homelab/tree/main/apps/backstage
      icon: github
spec:
  type: kubernetes-manifest
  owner: group:default:engineering
  lifecycle: homeprod