namespace: backstage
resources:
- namespace.yaml
- 1passwordItem.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- service-account.yaml

labels:
  - pairs:
      app: backstage
      'backstage.io/kubernetes-id': 'backstage'