# write a serviceAccount manifest for backstage that consumes the backstage-read-only clusterRole
#
kind: ServiceAccount
apiVersion: v1
metadata:
  name: backstage
  namespace: backstage
  annotations:
    backstage.io/kubernetes-service-account: backstage
---
# write a clusterRoleBinding to connect the service account the the clusterRole
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backstage-read-only
subjects:
  - kind: ServiceAccount
    name: backstage
    namespace: backstage
roleRef:
  kind: ClusterRole
  name: backstage-read-only
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-read-only
rules:
  - apiGroups:
      - '*'
    resources:
      - pods
      - configmaps
      - services
      - deployments
      - replicasets
      - horizontalpodautoscalers
      - ingresses
      - statefulsets
      - limitranges
      - daemonsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-read-only
  namespace: backstage-read-only
  annotations:
    kubernetes.io/service-account.name: backstage-read-only
type: kubernetes.io/service-account-token
