apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calibre
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: https://github.com/JamesAtIntegratnIO/homelab.git
    targetRevision: HEAD
    path: apps/media/apps/calibre
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated: {}