namespace: pi-worker-1-cluster

resources:
  - namespace.yaml
  - mycluster.yaml
  - k0stmotron-control-plane.yaml
  - remote-cluster.yaml
  - machines.yaml
  # machinePools don't seem to work right now
  # - remote-machines.yaml
