apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: pi-worker-1
  namespace: pi-worker-1-cluster
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.1.0/22
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 192.168.4.0/22
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0smotronControlPlane
    name: pi-worker-1
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteCluster
    name: pi-worker-1