name: Generate Manifests

on:
  push:
    branches:
      - main
    paths:
      - 'core/**'
      - 'apps/**'
      - 'monitoring/**'
      - .github/workflows/generate-manifests.yaml

jobs:
  template_the_manifests:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - source_folder: core
            destination_branch: infra
          - source_folder: apps
            destination_branch: apps
          - source_folder: monitoring
            destination_branch: monitoring

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          ref: main

      - uses: jamesatintegratnio/kustomized-helm-action@main
        with:
          source_folder: ${{ matrix.source_folder }}
          branch: ${{ matrix.branch }}
          helm_version: v3.14.4
